from selenium.webdriver.common.by import By

enter_and_registration = (By.XPATH, "//button[text()='Вход и регистрация']")
no_account = (By.XPATH, "//button[text()='Нет аккаунта']")
create_account = (By.XPATH, "//button[text()='Создать аккаунт']")
login_button= (By.XPATH, "//button[text()='Войти']")
logout_button= (By.XPATH, "//button[text()='Выйти']")
advertisment = (By.XPATH, "//button[text()= 'Разместить объявление']")

email = (By.NAME, 'email')
password = (By.NAME, 'password')
repeat_password = (By.NAME, 'submitPassword')
email_error = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[1]")
password_error = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[2]")
repeat_password_error = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[3]")
email_error_text = (By.XPATH, "//span[text()='Ошибка']")
user_name = (By.XPATH, "//h3[@class='profileText name']")
user_avatar = (By.CSS_SELECTOR, "button.circleSmall")

message= (By.XPATH, "//h1[text()= 'Чтобы разместить объявление, авторизуйтесь']")
name_ad = (By.XPATH, "//input[@placeholder='Название']")
description_ad = (By.XPATH, "//textarea[@placeholder='Описание товара']")
price_av = (By.XPATH, "//input[@placeholder='Стоимость']")
city_dropdown = (By.XPATH, "//input[@name='city']")
city_msk = (By.XPATH, "//input[@name='city' and @value= 'Москва']")
category_dropdown = (By.XPATH, "//input[@name='category']")
category_avto = (By.XPATH, "//input[@name='category' and @value='Авто']")
publish = (By.XPATH, "//button[text()='Опубликовать']")
created_ad = (By.XPATH, "//h2[text()='Дом змей']")
radio_new = (By.XPATH,"//*[contains(text(),'Новое')]")