from selenium.webdriver.common.by import By

ENTER_AND_REGISTRATION = (By.XPATH, "//button[text()='Вход и регистрация']")
NO_ACCOUNT = (By.XPATH, "//button[text()='Нет аккаунта']")
CREATE_ACCOUNT = (By.XPATH, "//button[text()='Создать аккаунт']")
LOGIN_BUTTON = (By.XPATH, "//button[text()='Войти']")
LOGOUT_BUTTON = (By.XPATH, "//button[text()='Выйти']")
ADVERTISEMENT = (By.XPATH, "//button[text()= 'Разместить объявление']")

EMAIL = (By.NAME, 'email')
PASSWORD = (By.NAME, 'password')
REPEAT_PASSWORD = (By.NAME, 'submitPassword')
EMAIL_ERROR = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[1]")
PASSWORD_ERROR = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[2]")
REPEAT_PASSWORD_ERROR = (By.XPATH, "(//div[contains(@class, 'input_inputError')])[3]")
EMAIL_ERROR_TEXT = (By.XPATH, "//span[text()='Ошибка']")
USER_NAME = (By.XPATH, "//h3[@class='profileText name']")
USER_AVATAR = (By.CSS_SELECTOR, "button.circleSmall")

MESSAGE = (By.XPATH, "//h1[text()= 'Чтобы разместить объявление, авторизуйтесь']")
NAME_AD = (By.XPATH, "//input[@placeholder='Название']")
DESCRIPTION_AD = (By.XPATH, "//textarea[@placeholder='Описание товара']")
PRICE_AD = (By.XPATH, "//input[@placeholder='Стоимость']")
CITY_DROPDOWN = (By.XPATH, "//input[@name='city']")
CITY_MSK = (By.XPATH, "//input[@name='city' and @value= 'Москва']")
CATEGORY_DROPDOWN = (By.XPATH, "//input[@name='category']")
CATEGORY_AVTO = (By.XPATH, "//input[@name='category' and @value='Авто']")
PUBLISH = (By.XPATH, "//button[text()='Опубликовать']")
CREATE_AD = (By.XPATH, "//h2[text()='Дом змей']")
RADIO_NEW = (By.XPATH,"//*[contains(text(),'Новое')]")